### ISSUE TITLE
Compiling for OS X

### ISSUE THREAD

**Issue by rwolfe901** [klamonte/qodem#5]
Trying to build under xcode 7.1 for OS X "El Capitan" and getting the following errors when running make:

miniupnpc.c:558:41: error: use of undeclared identifier 'IP_MULTICAST_TTL'
        if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(t...
                                        ^
miniupnpc.c:584:44: error: use of undeclared identifier 'INADDR_NONE'
                        if(mc_if.s_addr != INADDR_NONE)
                                           ^
miniupnpc.c:587:65: error: use of undeclared identifier 'IP_MULTICAST_IF'
                                if(setsockopt(sudp, IPPROTO_IP, IP_MULTI...
                                                                ^
3 errors generated.
make[1]: *** [objs/miniupnpc.o] Error 1
make: *** [all-recursive] Error 1
Roberts-MacBook-Pro:qodem robertwolfe$

**Comment by klamonte** [comment]
Thanks for reporting this.  I've got Snow Leopard here, I will get the new codebase re-ported before the 1.0beta.

Chances are this is just a macro defined in the miniupnpc makefile that I did not bring over into the new build system.

**Comment by klamonte** [comment]
I was able to compile on Snow Leopard with XCode 3.2.6.  How does this work for you?

**Comment by rwolfe901** [comment]
On 2016-03-24 15:28, Kevin Lamonte wrote:
> I was able to compile on Snow Leopard with XCode 3.2.6. How does this
> work for you?
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/klamonte/qodem/issues/5#issuecomment-201005357

I have had it compiled on OSX with XCode 7.1 for quote some time now.  
It should be available for downloading from my BBS.

**Comment by klamonte** [comment]
Thanks!  Closing this one out.
